Repository nyj001012/minirt, pull requests merged in 2023-07, with the labels that each got.

#3 Feat: header 및 src 파일 추가
  include/print.h
  include/scene.h
  include/structures.h
  include/trace.h
  include/utils.h
  src/main.c
  src/print/print.c
  src/scene/canvas.c
  src/scene/object_create.c
  src/scene/scene.c
  src/trace/hit/hit.c
  src/trace/hit/hit_sphere.c
  src/trace/hit/normal.c
  src/trace/ray/phong_lighting.c
  src/trace/ray/ray.c
  src/util/object_utils.c
  src/util/vec3_utils.c
Labels: enhancement

#7 초기 파일 norminette 수정
  Makefile
  include/structures.h
  include/trace.h
  include/utils.h
  src/main.c
  src/scene/object_create.c
  src/scene/scene.c
  src/trace/hit/hit.c
  src/trace/hit/hit_sphere.c
  src/trace/hit/normal.c
  src/trace/ray/phong_lighting.c
  src/trace/ray/ray.c
  src/trace/ray/reflect.c
  src/util/vec3_utils.c
  src/utils/object/object_utils.c
  src/utils/vec3/vec3_constructor.c
  src/utils/vec3/vec3_divide.c
  src/utils/vec3/vec3_length.c
  src/utils/vec3/vec3_minus.c
  src/utils/vec3/vec3_mult.c
  src/utils/vec3/vec3_plus.c
  src/utils/vec3/vec3_utils.c
Labels: refactor

#17 Feat: 실린더 구현
  Makefile
  include/structures.h
  include/trace.h
  src/print/print.c
  src/scene/scene.c
  src/trace/hit/hit.c
  src/trace/hit/hit_cylinder.c
  src/trace/hit/hit_sphere.c
Labels: enhancement

#18 Feat: 카메라 수정, 평면 구현
  Makefile
  a.rt
  include/structures.h
  include/trace.h
  maps/H2O.rt
  maps/a.rt
  maps/shadow.rt
  src/main.c
  src/mlx/mlx_utils.c
  src/parsing/process_file.c
  src/parsing/put_acl.c
  src/parsing/put_object.c
  src/scene/scene.c
  src/trace/hit/hit.c
  src/trace/hit/hit_plane.c
  src/trace/ray/ray.c
Labels: enhancement

#21 Chore: 유효하지 않은 확장자 테스트 파일 추가
  maps/error/invalid_extension
Labels: documentation

#29 Feat: cone 구현
  Makefile
  bonus/include/mlx_utils_bonus.h
  bonus/include/parsing_bonus.h
  bonus/include/print_bonus.h
  bonus/include/scene_bonus.h
  bonus/include/structures_bonus.h
  bonus/include/trace_bonus.h
  bonus/include/utils_bonus.h
  bonus/src/main_bonus.c
  bonus/src/mlx/mlx_utils_bonus.c
  bonus/src/parsing/double_conversion_bonus.c
  bonus/src/parsing/get_xyz_bonus.c
  bonus/src/parsing/parsing_utils_bonus.c
  bonus/src/parsing/process_file_bonus.c
  bonus/src/parsing/put_acl_bonus.c
  bonus/src/parsing/put_object_bonus.c
  bonus/src/parsing/split_line_bonus.c
  bonus/src/print/print_bonus.c
  bonus/src/scene/canvas_bonus.c
  bonus/src/scene/object_create_bonus.c
  bonus/src/scene/object_create_bonus2.c
  bonus/src/scene/render_scene_bonus.c
  bonus/src/scene/scene_bonus.c
  bonus/src/trace/hit/hit_bonus.c
  bonus/src/trace/hit/hit_cone_bonus.c
  bonus/src/trace/hit/hit_cylinder_bonus.c
  bonus/src/trace/hit/hit_plane_bonus.c
  bonus/src/trace/hit/hit_sphere_bonus.c
  bonus/src/trace/hit/normal_bonus.c
  bonus/src/trace/ray/phong_lighting_bonus.c
  bonus/src/trace/ray/ray_bonus.c
  bonus/src/trace/ray/reflect_bonus.c
  bonus/src/utils/color/color3_utils_bonus.c
  bonus/src/utils/object/object_utils_bonus.c
  bonus/src/utils/vec3/vec3_constructor_bonus.c
  bonus/src/utils/vec3/vec3_divide_bonus.c
  bonus/src/utils/vec3/vec3_length_bonus.c
  bonus/src/utils/vec3/vec3_minus_bonus.c
  bonus/src/utils/vec3/vec3_mult_bonus.c
  bonus/src/utils/vec3/vec3_plus_bonus.c
  bonus/src/utils/vec3/vec3_utils_bonus.c
  maps/a.rt
  maps/cone.rt
  maps/ice_cream.rt
  maps/sp_pl_cy.rt
  minilibx/mlx_image.swiftsourceinfo
  minilibx/mlx_init.swiftsourceinfo
  minilibx/mlx_window.swiftsourceinfo
Labels: enhancement

#33 Feat: cone 밑면 추가
  bonus/include/trace_bonus.h
  bonus/src/trace/hit/hit_cone_bonus.c
  maps/cone.rt
Labels: enhancement
